stages:
  - build
  - package

build:
  image: runejuhl/lein-graal:git-21.1.0
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - ./build/cljfmt

package:
  image: runejuhl/groovy-generic-build
  stage: package
  only:
    refs:
      - master
      - build
  script:
    - make packages
  artifacts:
    paths:
      - ./cljfmt
      - ./dist/
