stages:
  - release

build:
  image: runejuhl/graalvm-lein:latest
  stage: release
  script:
    - lein uberjar
    - native-image -jar target/cljfmt-graalvm-standalone.jar -H:Name="cljfmt"
  artifacts:
    paths:
      - ./cljfmt
