stages:
  - build
  - package

build:
  image: runejuhl/graalvm-lein:latest
  stage: build
  except:
    - tags
  script:
    - make
  artifacts:
    paths:
      - ./cljfmt

package:
  image: runejuhl/graalvm-lein:latest
  stage: package
  only:
    refs:
      - master
      - tags
  script:
    - make packages
  artifacts:
    paths:
      - ./cljfmt
      - ./dist/
